#!/usr/bin/env python3

"""
atds.py
Creates the Stack, Queue, and Deque classes.
"""

__author__ = "Jack Naliboff"
__version__ = "1/22/24"

class Stack(object):
    
    def __init__(self):
        self.st = []
    
    def push(self, item):
        self.st.append(item)

    def pop(self):
        if len(self.st) > 0:
            return self.st.pop()

    def peek(self):
        if len(self.st) > 0:
            return self.st[-1]
        else:
            return None

    def size(self):
        return len(self.st)

    def is_empty(self):
        if len(self.st) == 0:
            return True
        else:
            return False
    
    def __repr__(self):
        return str(self.st)

class Queue(object):
    def __init__(self):
        self.queue = []

    def enqueue(self, item):
        self.queue.append(item)

    def dequeue(self):
        return self.queue.pop(0)

    def size(self):
        return len(self.queue)

    def is_empty(self):
        return len(self.queue) == 0

    def __repr__(self):
        return str(self.queue)
